INSERT INTO User (first_name, last_name, email, professor) VALUES
('Thomas', 'Stackhouse', 'thomas.stackhouse@kingland.com', true),
('Clifford', 'Berry', 'clifford.berry@test.com', true),
('Carrie', 'Catt', 'carrie.catt@test.com', true),
('John', 'Gustafson', 'john.gustafson@test.com', true),
('Elie', 'Aucock', 'eaucock0@google.com.br', false),
('Loydie', 'Farfalameev', 'lfarfalameev1@mysql.com', false),
('Gauthier', 'Isaacs', 'gisaacs2@linkedin.com', false),
('Armand', 'Dillet', null, false),
('Hoebart', 'MacTrusty', 'hmactrusty4@newyorker.com', false),
('Peta', 'Franzel', null, false),
('Woodrow', 'Isson', 'wisson6@thetimes.co.uk', false),
('Warden', 'Van Merwe', null, false),
('Merline', 'Edney', 'medney8@google.pl', false),
('Davon', 'Hawthorn', 'dhawthorn9@google.de', false),
('Lenard', 'Jones', 'ljonesa@weebly.com', false),
('Kirstin', 'Valens-Smith', 'kvalenssmithb@oracle.com', false),
('Ettore', 'Stangroom', 'estangroomc@ycombinator.com', false),
('Markus', 'Rash', 'mrashd@aboutads.info', false),
('Allis', 'Hessing', 'ahessinge@com.com', false),
('Gail', 'Corpes', 'gcorpesf@e-recht24.de', false),
('Bernadette', 'Errol', 'berrolg@squarespace.com', false),
('Lib', 'Binns', 'lbinnsh@phoca.cz', false),
('Nanny', 'Mcasparan', 'nmcasparani@histats.com', false),
('Barnabas', 'Ell', 'bellj@mapy.cz', false),
('Toni', 'Hawkswood', 'thawkswoodk@dagondesign.com', false),
('Cassius', 'Easey', 'ceaseyl@photobucket.com', false),
('Kathye', 'Gislebert', 'kgislebertm@discuz.net', false),
('Margalit', 'McGorman', 'mmcgormann@hugedomains.com', false),
('Sabina', 'Waddington', 'swaddingtono@google.co.uk', false),
('Rahel', 'Craigg', 'rcraiggp@nationalgeographic.com', false),
('Lucho', 'Blueman', 'lbluemanq@tripod.com', false),
('Aggi', 'Boddymead', 'aboddymeadr@biblegateway.com', false),
('Marissa', 'Lawles', 'mlawless@merriam-webster.com', false),
('Liva', 'Guise', null, false),
('Gerardo', 'Jaggard', 'gjaggardu@abc.net.au', false),
('Tab', 'Denisevich', 'tdenisevichv@cdc.gov', false),
('Tasia', 'Bruinsma', 'tbruinsmaw@etsy.com', false),
('Hermann', 'Mickleburgh', 'hmickleburghx@liveinternet.ru', false),
('Brad', 'Nockalls', 'bnockallsy@ed.gov', false),
('Tabby', 'Saffer', 'tsafferz@huffingtonpost.com', false),
('Ailee', 'Reddecliffe', 'areddecliffe10@google.ru', false),
('Bianca', 'Eskriet', 'beskriet11@amazon.de', false),
('Geri', 'Yglesias', 'gyglesias12@businessinsider.com', false),
('Mickey', 'Easum', 'measum13@sogou.com', false),
('Billie', 'Tulley', 'btulley14@etsy.com', false),
('Yard', 'Lemme', null, false),
('Jerry', 'Pleasaunce', 'jpleasaunce16@ebay.com', false),
('Lucila', 'Reddell', 'lreddell17@pen.io', false),
('Heath', 'Morrissey', 'hmorrissey18@ftc.gov', false);

INSERT INTO Class (name, department, code) VALUES
('Web Development Club', 'Computer Science', 'COMS404'),
('Technical Writing', 'English', 'ENGL340'),
('Asymptotic Expansions of Elliptic Integrals', 'Mathematics', 'MATH000'),
('Basics of Computing', 'Computer Engineering', 'COME310');