DROP TABLE IF EXISTS User;
CREATE TABLE User
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    email      VARCHAR(255) DEFAULT NULL,
    professor  BOOLEAN      DEFAULT FALSE
);

DROP TABLE IF EXISTS Class;
CREATE TABLE Class
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    department VARCHAR(255) NOT NULL,
    code       VARCHAR(7)   NOT NULL
);
